### ISSUE TITLE
Sugerencia: Clase Insertar

### ISSUE THREAD

**Issue by seon22break** [afroxi/calculadora-imc#1]
!!EY!! Vengo del grupo de Facebook de PHP quería realizar una sugerencia ya que he estado revisando el código y creo que una cosa que se podría mejorar (Si no es así , dímelo y así aprendo jeje). En la clase Registro:

Mi constructor sería el siguiente:

`     function __construct(float $peso, float $altura, float $imc, string $estado)
		{
			$this->conex = new Conexion();
			$this->conex = $this->conex->getConex();
                        $this->peso = $peso;
			$this->altura = $altura;
			$this->imc = $imc;
			$this->estado = $estado;
		}` 

Así en el método insertarDatos recogemos los atributos de la clase. 

No se porqué pero me parece más correcto. Yo también me encuentro aprendiendo buenas prácticas en PHP.

PD: Muy buena idea para aprender buenas prácticas.

Un saludo  amigo.

**Comment by afroxi** [comment]
Hola Seon, gracias por tomarte el tiempo de verlo. El código que pones en el constructor lo veo bien y si funcionaría siendo sincero, pero en caso de lo que hice es que al iniciar la página muestra una tabla que carga datos de la BD, por lo que en el index a principios puse una instancia de la clase Registro para poder cargar los datos. Y entonces aplicando tu constructor tendría que pasar los argumentos de los campos por ahí mismo, y como esta al inicio aún no he llenado los campos y no se enviaría nada o habría un error, o a pesar que a principios inicialices variables como vacíos se los pases al instanciar la clase Registro, y luego de la condición del isset(que se dea clic al botón), vuelvas a instanciar la clase y se los pases las mismas variables redefinidas con los valores de los campos, y creo yo que sucedería conflicto. Buena idea con lo del constructor, no use también constructor por que los atributos los puse privados y "según yo" no es bueno que se pase valor a los atributos privados en un constructor. Y solo es mi opinión amigo, puedes aplicar tu constructor, uno es libre de poder hacerlo, de eso se trata la programación, pero siempre tomar en cuenta algunas secuencias, saludos :+1: De aquí un tiempo tal ves suba un proyectito, ya algo con más orden en code u_u, a seguir aprendiendo amigo.

**Comment by seon22break** [comment]
Interesante reflexión jeje. Pero solo una pregunta ¿ Por que crees que no es bueno pasar valor a los atributos privados en el método constructor?. Revisando algunos programas de desarrolladores con mas experiencia, es una práctica habitual, que no digo que por ello sea correcta. 

PD : Yo me encuentro aprendiendo Laravel, pero trabajo habitualmente con PHP a si que si necesitas ayuda en el proyecto. Cuenta conmigo :)

**Comment by afroxi** [comment]
Bueno, como migro de Java, el IDE me sugería a que cuando colocaba atributos privados los ponga su Getter & Setter y no en un Constructor (aunque no se si hubiera problema, no he hecho la prueba :/), y varias veces que pasaba, se me quedo en la mente colocar siempre un Get & Set para cada atributo privado (como una manía xd). Claro amigo sería bueno, también quisiera aprender Laravel, pero antes creo que es recomendable saber algunas bases sobre el patrón MVC y estoy algo en eso.
