### ISSUE TITLE
Comentarios

### ISSUE THREAD

**Issue by mroblesdev** [afroxi/calculadora-imc#2]
Hola, me parecer bueno tu código, se ve muy limpio, aunque es un proyecto pequeño pero con esas bases y un poco de mejoras podrás realizar proyectos grandes.

Solo quería hacer una sugerencia en cuestión de la consulta de los registro, evita colocar en (*) al seleccionar la tabla, si no vas a utilizar todos ya que al crecer la tabla esa consulta tardará mucho.
`$query = "SELECT * FROM usuario ORDER BY imc_usuario DESC";`

También la parte donde muestras los datos de la tabla, tal vez se podría mejorar recorriéndolo con un `foreach`

```
foreach ($arr as $row) {
    <td><?= $row['peso_usuario']; ?></td>
 }
```
Y otra cosa aunque no tiene que ver con programación sino con base de datos, en tu tabla tienes un campo que se llama `estado_usuario` sería bueno que lo cambiaras por una llave foránea haciendo referencia a un catalogo que contenga los estados que se utilizaran. Y en base a esto hacer el CRUD de ese catálogo para ver como lo trabajarás con 2 tablas y varías vistas.

Solo es mi humilde opinión.

Sigue así. Saludos

**Comment by afroxi** [comment]
Hola Marko, muchas gracias por tu opinión. Y si tienes razón en eso de la consulta en solo seleccionar lo que solo se va usar y mostrar, estaba acostumbrado en poner *, por que pensaba que en algún momento quizá necesitaré los demás datos, pero al pasar los días me doy cuenta que no. Claro foreach, gracias por la recomendación, no se como lo había olvidado. Entonces, crear una tabla catalogo? la cual según el estado se mostraría algunos productos o algo así?. Trataré de actualizarlo pronto, encontraré tiempo largo en un fin de semana para poder hacer cambios.
